### ISSUE TITLE
Address data not up to date?

### ISSUE THREAD

**Issue by wolfbert** [JOSM/austriaaddresshelper#16]
Example: https://www.openstreetmap.org/way/559023274

[Austrian Address Register ](https://www.adressregister.at/adressregister/) reports "St. Pölten, Zwerndorf, Allandstraße 21".
Plugin reports "Zwerndorf, Zwerndorf 21".

Edit: Also, Zwerndorf is set in `addr:street`, not `addr:place`.

**Comment by pkolmann** [comment]
Hi,

if you take a look at https://bev.kolmann.at/map/#20/48.22868/15.72218 you will see that there are 2 Addresses definded in the Austrian Address Register.

Zwerndorf 21 is directly in the middle of the house, Allandstraße 21 is in front of the house. Since the API returns only the closest address, the node within the house is returned.

Please contact the local Gemeindeamt, to fix this in their Data. After they have fixed the data, with the next BEV export, it should be fixed.

![image](https://github.com/JOSM/austriaaddresshelper/assets/2240760/48c68c58-bd10-4b67-bc19-9d40a85c7d2d)

**Comment by wolfbert** [comment]
@pkolmann Thanks for the link to your map, very helpful. 

I believe the difference in the data may be caused by the address geocoding process (guidelines described in [Adressregister Leitfaden für Gemeinden](https://www.bev.gv.at/dam/jcr:46658c21-0b0b-42f4-bba9-16b86e95a694/ADRESSREGISTER_LEITFADEN.PDF)). As far as I understand, the location should now be the access point to the building, not the building itself. Also, prior to construction the address is just put somewhere near the closest street.

And yes, the local authorities should probably fix that.
