### ISSUE TITLE
Question about privacy

### ISSUE THREAD

**Issue by hubgitti** [JOSM/austriaaddresshelper#6]
Hi,

first of all: Your address helper tool is just awesome!

I have a question about privacy: Lately, I got a temporary error message, complaining about not able to connect to some server.

Where is your tool connecting to (which servers), what kind of privacy relevant data is sent? At least it is the OSM user IP, but what else?

Thanks for your great tool, and for your information!

**Comment by thomaskonrad** [comment]
Hi!

I'm glad you find the tool useful!

That error message must have popped up during a server maintenance i did lately. I had to reboot the machine due to a kernel update.

The tool is only connecting to my server. The URL is https://bev-reverse-geocoder.thomaskonrad.at and the connection is protected via TLS.

The only info I get on the server side is the GPS coordinates you want to fetch the address for and the IP address you are connecting from. That's all. Neither your OSM user name nor any other data that can easily be used to identify you is sent by (the IP address could be used for that in theory, but I don't have access to any provider's data).

**Comment by hubgitti** [comment]
Thanks for your answer!
